"""Reproducible V1 demo scenarios (real TRAIN data, default app budget 10 x 8, seed 0).

    python -m app.demo_scenarios                 # prints a summary and writes docs/v1_demo_evidence.json

The scenarios run through the same service entry point as the Streamlit app (`generate_recommendations`). Scenario S8 is
SYNTHETIC: it corrupts a temporary COPY of one processed file to show the data-error path; real data is never modified.
"""
from __future__ import annotations

import json
import platform
import shutil
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from app.adapters import DEFAULT_PROCESSED_DIR, REQUIRED_FILES, DataLoadError, field_availability, load_app_data  # noqa: E402
from app.service import AppConfig, generate_recommendations  # noqa: E402

SCENARIOS = [
    {"id": "S1", "title": "Successful generation (all roles agree, zero detected violations)",
     "request": {"target_segment": "men", "detail_category": "tshirt_polo", "preferred_dominant_material": "cotton", "breathability": "high"}},
    {"id": "S2", "title": "Intent-focused and Sorting-focused select different candidates",
     "request": {"target_segment": "women", "detail_category": "trousers", "preferred_dominant_material": "linen", "fit": "relaxed",
                 "breathability": "high"}},
    {"id": "S3", "title": "Empty TRAIN template pool",
     "request": {"target_segment": "baby", "detail_category": "skirts"}},
    {"id": "S4", "title": "Invalid preferences (API / JSON request; the UI form cannot produce these values)",
     "request": {"target_segment": "women", "detail_category": "trousers", "fit": "skinny", "water_repellent": "yes"}},
    {"id": "S5", "title": "Conflicting preferences (possible in the UI form)",
     "request": {"target_segment": "women", "detail_category": "trousers", "preferred_dominant_material": "linen",
                 "forbidden_materials": ["linen", "elastane"], "stretch": "high"}},
    {"id": "S6", "title": "Black colour: SR4 colour flag prevents zero violations",
     "request": {"target_segment": "women", "detail_category": "dresses", "preferred_dominant_material": "viscose", "colour": "black"}},
    {"id": "S7", "title": "Preference unavailable for the category (sent via API; disabled in the UI)",
     "request": {"target_segment": "women", "detail_category": "socks_hosiery", "fit": "relaxed", "stretch": "low"}},
]


def summarise(result: dict) -> dict:
    return {
        "status": result["status"],
        "messages": [{"level": m["level"], "text": m["text"]} for m in result["messages"]],
        "stats": {k: result["stats"].get(k) for k in ("train_garments_in_cell", "eligible_templates", "templates_used", "candidates_requested",
                                                       "candidates_generated", "hard_valid", "front_size") if k in result["stats"]},
        "recommendations": [{
            "roles": r["role_titles"], "candidate_id": r["candidate_id"], "template_garment_id": r["template_garment_id"],
            "colour": r["colour"], "fit": r["fit"], "length": r["length"],
            "composition": [f"{c['component']}: {c['text']}" for c in r["composition"]],
            "intent_0_100": r["intent_0_100"], "plausibility_0_100": r["plausibility_0_100"], "violation_count": r["violation_count"],
            "sorting_summary": r["sorting_summary"],
            "preferences": [f"{p['preference']}={p['requested']}: {p['status']}. {p['explanation']}" for p in r["preferences"]],
            "changes_from_template": r["changes_from_template"], "confirmed_rule_changes": r["confirmed_rule_changes"],
        } for r in result["recommendations"]],
        "digest": result.get("digest"),
    }


def synthetic_corruption_scenario(processed_dir: Path) -> dict:
    """S8 (SYNTHETIC): copy the processed files to a temp folder, overwrite the COPY of the parquet with invalid bytes."""
    with tempfile.TemporaryDirectory() as tmp:
        for name in REQUIRED_FILES:
            shutil.copy(processed_dir / name, Path(tmp) / name)
        (Path(tmp) / "garment_representation.parquet").write_bytes(b"synthetic corruption for the V1 demo")
        try:
            load_app_data(Path(tmp))
            return {"status": "loaded (unexpected)"}
        except DataLoadError as e:
            return {"status": "data_error", "file": e.file, "problem": e.problem.split(" (")[0]}


def run(processed_dir: Path = DEFAULT_PROCESSED_DIR, out: Path | None = ROOT / "docs" / "v1_demo_evidence.json") -> dict:
    data = load_app_data(processed_dir)
    cfg = AppConfig()
    evidence = {"note": "Generated by `python -m app.demo_scenarios` on real TRAIN data; default budget 10 x 8, seed 0.",
                "python": platform.python_version(), "budget": {"n_templates": cfg.n_templates, "candidates_per_template": cfg.candidates_per_template},
                "seed": 0, "scenarios": []}
    for sc in SCENARIOS:
        res = generate_recommendations(sc["request"], seed=0, data=data, app_cfg=cfg)
        evidence["scenarios"].append({"id": sc["id"], "title": sc["title"], "request": sc["request"], "observed": summarise(res)})
    evidence["ui_field_availability_socks_hosiery"] = {k: v["enabled"] for k, v in field_availability("socks_hosiery", data.capabilities).items()}
    evidence["scenarios"].append({"id": "S8", "title": "SYNTHETIC: corrupted copy of garment_representation.parquet",
                                  "request": None, "observed": synthetic_corruption_scenario(Path(processed_dir))})
    if out is not None:
        out.write_text(json.dumps(evidence, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
    return evidence


if __name__ == "__main__":
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")       # Windows consoles / redirected output
    ev = run()
    for s in ev["scenarios"]:
        o = s["observed"]
        print(f"{s['id']}: {s['title']} -> {o['status']}")
        for m in o.get("messages", []):
            print(f"   [{m['level']}] {m['text']}")
        for r in o.get("recommendations", []):
            print(f"   {' + '.join(r['roles'])}: intent {r['intent_0_100']}, plausibility {r['plausibility_0_100']}, "
                  f"violations {r['violation_count']}, {r['composition']}")
